global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "medplum"
    static_configs:
      - targets: ["10.11.0.15:5555"]
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']